[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "/api/chat"
  function = "ai-chat"

[[functions]]  
  path = "/api/train"
  function = "train-ai"
