[build]
functions = "netlify/functions"
publish = "."

command = "npx @11ty/eleventy --input=benches --output=benches"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/"
to = "/meet/"
status = 301
