[build]
  functions = "netlify/functions"
  publish = "."
  
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  
[build]
  command = "npx @11ty/eleventy --input=Benches" 
  publish = "Benches/_site" 
