[build]
  functions = "netlify/functions"
  publish = "."
  
  command = "npx @11ty/eleventy --input=benches --output=."

  
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  # ✅ FIX: Leitet die gewünschte URL auf den Ort um, den Eleventy erstellt.
  # Dies behebt den 404-Fehler, während die URL im Browser gleich bleibt.
  from = "/meet.html"
  to = "/meet/index.html"
  status = 200 # Wichtig: 200 (Rewrite), nicht 302 (Redirect)

[[redirects]]
  from = "/"
  to = "/meet.html"
  status = 302

[[redirects]]
  from = "/*.njk"
  to = "/:splat.html"
  status = 301
