[build]
  functions = "netlify/functions"
  publish = "."
  
  command = "npx @11ty/eleventy --input=benches" 

  
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  
