[build]
  functions = "netlify/functions"
  publish = "."
  
  command = "npx @11ty/eleventy --input=benches --output=."

  
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  

[[redirects]]
  from = "/"
  to = "/meet.html"
  status = 302

[[redirects]]
  from = "/*.njk"
  to = "/:splat.html"
  status = 301
