[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "/api/chat"
  function = "ai-chat"

[[functions]]  
  path = "/api/train"
  function = "train-ai"
  
[[functions]]
  schedule = "@hourly"
  function = "train-ai"

# Redirects
[[redirects]]
  from = "/api/train"
  to = "/.netlify/functions/train-ai"
  status = 200
  force = true

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/ai-chat"
  status = 200
  force = true
